
import java.awt.Container;

/*
 * MovieFrame.java
 *
 * Created on 2016年3月29日, 上午6:19
 */



/**
 *
 * @author  Administrator
 */
public class MovieFrame extends javax.swing.JFrame {
    
    /** Creates new form MovieFrame */
    public MovieFrame() {
        initComponents();
        setLocation(this);
    }
         public static void setLocation(Container container){
        java.awt.Dimension screen=java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension Dcontainer=container.getSize();
        if(Dcontainer.height>screen.height){
            Dcontainer.height=screen.height;
        }
        if(Dcontainer.width>screen.width){
            Dcontainer.width=screen.width;
        }
        container.setLocation((screen.width-Dcontainer.width)/2,(screen.height-Dcontainer.height)/2);
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmMovieType = new javax.swing.JMenu();
        jmiAddType = new javax.swing.JMenuItem();
        jmiEditType = new javax.swing.JMenuItem();
        jmMovieInfo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmMovieType.setText("电影类型");

        jmiAddType.setText("添加");
        jmiAddType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddTypeActionPerformed(evt);
            }
        });
        jmMovieType.add(jmiAddType);

        jmiEditType.setText("编辑");
        jmMovieType.add(jmiEditType);

        jMenuBar1.add(jmMovieType);

        jmMovieInfo.setText("电影信息");
        jmMovieInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMovieInfoActionPerformed(evt);
            }
        });

        jMenuItem1.setText("查询");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmMovieInfo.add(jMenuItem1);

        jMenuBar1.add(jmMovieInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAddTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddTypeActionPerformed
        // TODO add your handling code here:
        MovieTypeFrame type=new MovieTypeFrame();
        type.setResizable(false);
        setLocation(type);
        type.setVisible(true);
    }//GEN-LAST:event_jmiAddTypeActionPerformed

    private void jmMovieInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMovieInfoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jmMovieInfoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         MovieInfoFrame info=new MovieInfoFrame();
        info.setResizable(false);
        setLocation(info);
        info.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmMovieInfo;
    private javax.swing.JMenu jmMovieType;
    private javax.swing.JMenuItem jmiAddType;
    private javax.swing.JMenuItem jmiEditType;
    // End of variables declaration//GEN-END:variables
    
}
