
import java.sql.Connection;
import java.sql.PreparedStatement;

/*
 * MovieTypeFrame.java
 *
 * Created on 2016年3月29日, 上午6:42
 */
import javax.swing.JOptionPane;



/**
 *
 * @author  Administrator
 */
public class MovieTypeFrame extends javax.swing.JFrame {
    
    /** Creates new form MovieTypeFrame */
    public MovieTypeFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblMovieType = new javax.swing.JLabel();
        jtfMovieType = new javax.swing.JTextField();
        jbAddType = new javax.swing.JButton();
        jbExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblMovieType.setText("电影类型：");

        jbAddType.setText("添加");
        jbAddType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddTypeActionPerformed(evt);
            }
        });

        jbExit.setText("退出");
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jlblMovieType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfMovieType, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jbAddType)
                .addGap(38, 38, 38)
                .addComponent(jbExit)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMovieType)
                    .addComponent(jtfMovieType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExit)
                    .addComponent(jbAddType))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
      
    }//GEN-LAST:event_jbExitActionPerformed

    private void jbAddTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddTypeActionPerformed
        // TODO add your handling code here:
        int i = 0;
        MovieType type=new MovieType();
        String tn=this.jtfMovieType.getText().trim();
        type.setTypeName(tn);
        Connection con=null;
        PreparedStatement pstmt=null;
        String sql="insert into type values(?)";
        
        try{
            con=MovieDB.getCon();
            pstmt=con.prepareStatement(sql);
            pstmt.setString(1,type.getTypeName());
            
            i=pstmt.executeUpdate();
        }catch(Exception ex){
            ex.printStackTrace();
        }finally{
            try{
                pstmt.close();
                con.close();
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }
        if(i>0){
            JOptionPane.showMessageDialog(null, "添加成功！");
        }else
        {
            JOptionPane.showMessageDialog(null, "添加失败！");
        }

    }//GEN-LAST:event_jbAddTypeActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieTypeFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAddType;
    private javax.swing.JButton jbExit;
    private javax.swing.JLabel jlblMovieType;
    private javax.swing.JTextField jtfMovieType;
    // End of variables declaration//GEN-END:variables
    
}
